var map=new BMap.Map("allmap",{minZoom:12,maxZoom:15});window.map=map;var point=new BMap.Point(116.375128,39.924407);map.enableScrollWheelZoom();map.centerAndZoom(point,12);map.setMapStyle({styleJson:metroStyle});var icons=[new BMap.Icon("./asset/img/redsubway_64.png",new BMap.Size(64,64),{anchor:new BMap.Size(10,65)}),new BMap.Icon("./asset/img/subway_48.png",new BMap.Size(48,48),{anchor:new BMap.Size(10,45)}),new BMap.Icon("./asset/img/subway_32.png",new BMap.Size(32,32),{anchor:new BMap.Size(10,25)}),new BMap.Icon("./asset/img/subway_24.png",new BMap.Size(24,24),{anchor:new BMap.Size(10,25)}),new BMap.Icon("./asset/img/subway_16.png",new BMap.Size(16,16),{anchor:new BMap.Size(10,10)})]
function addMarker(item){var myIcon="";item.range<11?myIcon=icons[0]:item.range<50?myIcon=icons[2]:item.range<100?myIcon=icons[3]:myIcon=icons[4];var marker=new BMap.Marker(new BMap.Point(item.point.lng,item.point.lat),{icon:myIcon});if(item.range<11){marker.setTop(true);var label=new BMap.Label(item.range,{offset:new BMap.Size(10,25)});label.setStyle({color:"#fff",backgroundColor:"none",fontSize:"14px",fontWeight:"bold",height:"20px",lineHeight:"20px",fontFamily:"微软雅黑",border:"none"});marker.setLabel(label);}
var content="<p>签到次数排名:"+item.range+"</p><p>签到次数:"+item.checkin_num+"</p><p>照片数："+item.photo_num+"</p>";map.addOverlay(marker);var opts={title:"<h2>"+item.title+"</h2>",enableMessage:false};addClickHandler(content,marker,opts);}
function addClickHandler(content,marker,opts){marker.addEventListener("click",function(e){openInfo(content,e,opts)});}
function openInfo(content,e,opts){var p=e.target;var point=new BMap.Point(p.getPosition().lng,p.getPosition().lat);var infoWindow=new BMap.InfoWindow(content,opts);map.openInfoWindow(infoWindow,point);}
var points=[];translateCallback=function(point,item){item.point=point;delete item.lon;delete item.lat;points.push(item);}
function ZoomControl(){this.defaultAnchor=BMAP_ANCHOR_TOP_LEFT;this.defaultOffset=new BMap.Size(10,10);}
ZoomControl.prototype=new BMap.Control();ZoomControl.prototype.initialize=function(map){var div=document.createElement("div");div.id="citymetro";div.innerHTML="<button class=\"btn btn-success\" onclick='showMetor(0)'>北京</button><button class=\"btn btn-success\" onclick='showMetor(1)'>上海</button><button class=\"btn btn-success\" onclick='showMetor(2)'>广州</button><button class=\"btn btn-success\" onclick='showMetor(3)'>深圳</button><button class=\"btn btn-success\" onclick='showMetor(4)'>南京</button>"
div.style.cursor="pointer";div.style.border="none";div.style.backgroundColor="none";map.getContainer().appendChild(div);return div;}
var myZoomCtrl=new ZoomControl();map.addControl(myZoomCtrl);function showMetor(e){var points=[new BMap.Point(116.375128,39.924407),new BMap.Point(121.475826,31.238047),new BMap.Point(113.303051,23.142116),new BMap.Point(114.075345,22.573222),new BMap.Point(118.793022,32.060419)];var name=["bjmetro","shhmetro","gzmetro","szmetro","njmetro"]
map.centerAndZoom(points[e],12);var data;e==0?data=beijing:e==1?data=shanghai:e==2?data=guangzhou:e==3?data=shengzhen:data=nanjing;data.forEach(function(item){addMarker(item);});}
showMetor(0);